version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.2.1
    steps:
      - run: 
          name: "Set ISHIKO_PLATFORM environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/platform && echo 'export ISHIKO_PLATFORM="/projects/ishiko/platform"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/platform/adl
      - run:
          name: Build
          command: cd /projects/ishiko/platform/adl/cpp/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/platform/adl/cpp/tests/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/platform/adl/cpp/tests/build/gnumake && ./IshikoErrorsTests
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
